### PR TITLE
Fix randomization in bucketization algorithm

### PR DESCRIPTION
**Pull request by mjgiarlo**
Minters using non-sequential templates use a number of containers with an equal number of identifiers as a way to split up the identifier space into manageable chunks (or "buckets") and to increase the appearance of randomness in the identifiers.

As an example, let's assume a non-sequential identifier template that has 100 possible values. It might have 10 buckets each with 10 identifiers.  You would expect sequential calls to `#mint` not to continually spit out identifiers that look the same, and yet this is precisely the behavior that we now see with stateful minters.

Stateful minters with non-sequential templates are currently spitting out very similar-looking identifiers because every call to `#mint` reuses the same random number (for replayability purposes) **and** fails to take into account how far into the sequence it is (despite that being part of its saved state). As a result, these minters will choose one bucket and keep using it until it is exhausted. This can and has been causing problems upstream (see: https://github.com/projecthydra-labs/active_fedora-noid/issues/5 and https://github.com/projecthydra/sufia/pull/1037).

Thus, stateful minters ought to consider position in the sequence when grabbing a random bucket. This PR uses the value of the `seq` param (from the passed-in state) and the `#next_random` method to accomplish this, which has the benefit of **not** breaking current minters that are already into their sequence, but has a potential downside of needing to run `#next_random` many (possibly thousands) of times to advance the minter in its sequence.  I did this to respect current minters and not break their state.

Another solution might be to completely rethink how we handle random number generation -- for instance, my first pass at this PR changed the seed on every call to mint by seeding the random number generator with the original seed value (persisted by the `#dump` method) plus the sequence value. With that scheme, every call to `#mint` only needs to generate a single random number rather than manually replay it.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Not satisfied with some of the choices I made. Gonna rework this tomorrow.

Please do not merge.

**Comment by hackmastera** [comment]
@mjgiarlo thanks so much for taking this on. I assume you have a pretty good understanding of this minting algorithm now; a general overview-type comment would be a great addition.

**Comment by cbeer** [comment]
It'd also be good if you could disentangle the functional changes from the style changes (into separate commits)

**Comment by mjgiarlo** [comment]
@cbeer Those are exactly some of the choices I was talking about.  Hope to have another PR ready in a couple hours.

@hackmastera I can add some YARD docs too. If I space on that, let me know again. ;)

**Comment by cbeer** [comment]
@mjgiarlo cool -- and, for the record, I fully support bringing the code quality up to current standards.

**Comment by dbrower** [comment]
@mjgiarlo I wrote a bunch of stuff when I went through and figured out how it worked. Feel free to lift any or as much as you'd like. There are a few differences from the ruby one, but they are marked as extensions. 

https://github.com/ndlib/noids/blob/master/noid-service.md#noid-template-format
https://github.com/ndlib/noids/blob/master/noid/noid.go#L228-L238

in that implementation i removed the randomness all together and took ids from each bucket in turn to make sure ids were more equally scattered throughout the identifer-space.

**Comment by mjgiarlo** [comment]
@hackmastera Check out the comment I left up above and let me know how far that gets us down the road of documenting how randomization/bucketization/minting work. Let me know if there are any gaps and I can address those.

**Comment by hackmastera** [comment]
@mjgiarlo your comment is quite helpful. This sentence is a little confusing:
"a number of containers with an equal number of identifiers" -- I thought at first you meant the number of containers == the number of identifiers in each, which didn't seem possible.
Should probably be "a number of containers, each with an equal number of identifiers"

I think if you remove the part about how it used to work, it would be helpful to put this comment at the top of minter.rb.

Can you elaborate on "potential downside of needing to run #next_random many (possibly thousands) of times to advance the minter in its sequence"? Do you know anything about the scenario in which this would happen? Are there ways to make it less likely?

Thank you!

**Comment by mjgiarlo** [comment]
@hackmastera ++

OK, will clarify that sentence and paste it into minter.rb.  Thanks!

Re: the potential downside, this happens every single time you call `#mint` with a stateful minter (a minter initialized with state passed in as a param) and a non-sequential template. This is what we have in Sufia. So if you have an app with 1,000 identifiers, and you mint another, the first thing the minter does is fast-forward the random number sequence 1,000 spots. It should be a speedy operation because it's the kind of thing computers are good at, but it will degrade at some point.

I believe @cbeer is working on a PR that may address this. Fixing the prior bug without touching lots of other code and refactoring things, and possibly breaking minters with existing state, was my first priority, and now I'd like to have another go at improving things efficiency/performancewise, though until someone says they're seeing performance-related issues with 0.7.2, I'd be content to backburner this work.

**Comment by mjgiarlo** [comment]
@hackmastera PR added: https://github.com/microservices/noid/pull/18 I'd be much obliged if you could review it for clarity and substance!

**Comment by mjgiarlo** [comment]
FWIW, I'm not seeing a very large performance penalty after benchmarking into the 100s of 1000s. The benchmarking code and results are here:

https://gist.github.com/mjgiarlo/1b09f710a625ffb92a8f

**Pull request merged**
